
version: 0.2

env:
  variables:
    IMAGE: "hemgit/tomcat"
    SSH_USER: "devops"
    EC2_HOST: "1.2.3.4"

  secrets-manager:
    DOCKERHUB_USERNAME: "dockerhub/username"
    DOCKERHUB_PASSWORD: "dockerhub/password"
    SSH_PRIVATE_KEY: "ssh/ec2/ci-key"

phases:
  install:
    commands:
      - yum install -y openssh-clients || apt-get update && apt-get install -y openssh-client
  pre_build:
    commands:
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
      - TAG=$(cat TAG.txt); export TAG; echo "TAG=$TAG"

  build:
    commands:
      - |
        ssh "$SSH_USER@$EC2_HOST" bash -c "'
          set -e
          export DOCKER_CONFIG=\$(mktemp -d)
          echo \"$DOCKERHUB_PASSWORD\" | docker login -u \"$DOCKERHUB_USERNAME\" --password-stdin
          docker push $IMAGE:$TAG
          docker logout || true
          rm -rf \"\$DOCKER_CONFIG\"
        '"
artifacts:
  files:
    - TAG.txt
